name: nat_info
description: A package to get public IP of nat and derive its port mapping scheme.
version: 0.2.1
author: C.J. Rossouw <chris.rossouw5@gmail.com>
homepage: https://github.com/TheLonelyNull/nat_info

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

